name: Generate ASCII Artwork by Multiple Jobs

on: 
    push

env:
    ANIMAL_NAME: sheep

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps: 
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y
          
        - name: Execute Cowsay CMD
          run: cowsay -f $ANIMAL_NAME "Run for cover, I am a DRAGON.....RAWR" >> $ANIMAL_NAME.txt
        
        - name: Upload Dragon Text File
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: $ANIMAL_NAME.txt


    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps: 
        - name: Download Dragon Text File
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Test File Exists
          run: grep -i "$ANIMAL_NAME" $ANIMAL_NAME.txt
  
    deploy_job_3:
        needs: [build_job_1, test_job_2]
        runs-on: ubuntu-22.04
        steps: 
        - name: Download Dragon Text File
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file 

        - name: Read File
          run: cat ${{ env.ANIMAL_NAME }}.txt

        - name: Deploy
          run: echo Deploying ... .. .