name: Workflow Filters and Activities

on: 
    workflow_dispatch:
    schedule:
        - cron: "*/58 * * * *"
    push:
        branches: 
            - main
            - '!feature/*'  # ignoring pushing to any branch name starting with featrue using !
        
        
        # branches-ignore:
        #     - feature/*   # feataure/add-feature, feature/update-images
        #     - test/**     # test/ui/index, test/checkout/payment/
    pull_request:
        types: 
            - opened
            - closed
        paths-ignore:   # workflow will only run when a pull request that includes a chagne on any file other than README.md
            - README.md
        branches:       # configures your workflow to only run on pull requestes that target specific branches.
            - main

jobs:
    hello: 
        runs-on: ubuntu-latest
        steps:
        - run: echo This workflow/job/step is execueted for event type - ${{ github.event_name }}